### ISSUE TITLE
Cant build wizard

### ISSUE THREAD

**Issue by ggnery** [titzer/wizard-engine#159]
Hi, 
I was trying to build wizard with this tutorial (https://github.com/titzer/wizard-engine/blob/master/doc/Building.md), but all i got was this error bellow. I tryed the recomendations in case of error, but all i got was that "vctags not found"

gnery@gnery-Vivobook:~/Desktop/Projeto_pesquisa/wizard-engine$ make -j
vctags -e src/engine/*.v3 src/engine/v3/*.v3 src/util/*.v3 src/wave/*.v3 src/wasi/*.v3 src/jawa/*.v3 src/engine/*.v3 src/engine/v3/*.v3 src/util/*.v3 test/spectest/*.v3 test/spectest.main.v3 src/engine/*.v3 src/engine/v3/*.v3 src/util/*.v3 src/jawa/*.v3 test/unittest/*.v3 test/spectest/*.v3 test/unittest.main.v3 src/wasi/x86-64-linux/*.v3 src/engine/x86-64/*.v3
./build.sh spectest x86-linux
./build.sh wizeng x86-linux
./build.sh unittest x86-linux
./build.sh objdump x86-linux
./build.sh spectest x86-64-linux
./build.sh wizeng x86-64-linux
./build.sh unittest x86-64-linux
./build.sh objdump x86-64-linux
./build.sh spectest jvm
./build.sh wizeng jvm
./build.sh unittest jvm
./build.sh objdump jvm
./build.sh spectest x86-linux
./build.sh wizeng x86-linux
./build.sh unittest x86-linux
./build.sh objdump x86-linux
./build.sh spectest x86-64-linux
./build.sh wizeng x86-64-linux
./build.sh unittest x86-64-linux
./build.sh objdump x86-64-linux
./build.sh spectest jvm
./build.sh wizeng jvm
./build.sh unittest jvm
./build.sh objdump jvm
[src/monitors/MemStatsMonitor.v3 @ 124:30] ParseError: ',' or ';' expected
def log2_WASM_PAGE_SIZE = 16u6;
                             ^
make: *** [Makefile:68: bin/wizeng.x86-linux] Error 1
make: *** Waiting for unfinished jobs....
[src/monitors/MemStatsMonitor.v3 @ 124:30] ParseError: ',' or ';' expected
def log2_WASM_PAGE_SIZE = 16u6;
                             ^
make: *** [Makefile:42: bin/wizeng.jvm] Error 1
[src/monitors/MemStatsMonitor.v3 @ 124:30] ParseError: ',' or ';' expected
def log2_WASM_PAGE_SIZE = 16u6;
                             ^
cp: cannot stat 'bin/wizeng.x86-64-linux': No such file or directory
warning: could not pregen code into bin/wizeng.x86-64-linux, may be slower (see bin/wizeng.x86-64-linux.pregen)
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:35] UnresolvedMember: type Pointer has no such member "atRef"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                  ^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:56] UnresolvedOp: operator "+" cannot be found for type "?"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                                       ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:46] UnresolvedOp: operator "-" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:62] UnresolvedOp: operator "&" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:40] TypeError: type cast always fails
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                       ^
[src/engine/x86-64/X86_64Stack.v3 @ 725:65] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		return Ref<X86_64InterpreterFrame>.of(CiRuntime.forgeRange<byte>(sp, X86_64InterpreterFrame.size));
                                                                ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 27:61] UnresolvedMember: type CiRuntime has no such member "forgeRange"
			platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(bytes)));
                                                            ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 61:53] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(cur_bytes + add_bytes)));
                                                    ^^^^^^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:35] UnresolvedMember: type Pointer has no such member "atRef"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                  ^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:56] UnresolvedOp: operator "+" cannot be found for type "?"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                                       ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:46] UnresolvedOp: operator "-" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:62] UnresolvedOp: operator "&" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:40] TypeError: type cast always fails
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                       ^
[src/engine/x86-64/X86_64Stack.v3 @ 725:65] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		return Ref<X86_64InterpreterFrame>.of(CiRuntime.forgeRange<byte>(sp, X86_64InterpreterFrame.size));
                                                                ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 27:61] UnresolvedMember: type CiRuntime has no such member "forgeRange"
			platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(bytes)));
                                                            ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 61:53] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(cur_bytes + add_bytes)));
                                                    ^^^^^^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:35] UnresolvedMember: type Pointer has no such member "atRef"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                  ^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:56] UnresolvedOp: operator "+" cannot be found for type "?"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                                       ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:46] UnresolvedOp: operator "-" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:62] UnresolvedOp: operator "&" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:40] TypeError: type cast always fails
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                       ^
[src/engine/x86-64/X86_64Stack.v3 @ 725:65] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		return Ref<X86_64InterpreterFrame>.of(CiRuntime.forgeRange<byte>(sp, X86_64InterpreterFrame.size));
                                                                ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 27:61] UnresolvedMember: type CiRuntime has no such member "forgeRange"
			platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(bytes)));
                                                            ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 61:53] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(cur_bytes + add_bytes)));
                                                    ^^^^^^^^^^
Command 'vctags' not found, did you mean:
  command 'ctags' from snap universal-ctags (0.2024-02-26+08:12:05+5d8c5927a)
  command 'ctags' from deb exuberant-ctags (1:5.9~svn20110310-16ubuntu0.22.04.1)
  command 'ctags' from deb universal-ctags (5.9.20210829.0-1)
See 'snap info <snapname>' for additional versions.
[src/monitors/MemStatsMonitor.v3 @ 124:30] ParseError: ',' or ';' expected
def log2_WASM_PAGE_SIZE = 16u6;
                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:35] UnresolvedMember: type Pointer has no such member "atRef"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                  ^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:56] UnresolvedOp: operator "+" cannot be found for type "?"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                                       ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:46] UnresolvedOp: operator "-" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:62] UnresolvedOp: operator "&" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:40] TypeError: type cast always fails
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                       ^
[src/engine/x86-64/X86_64Stack.v3 @ 725:65] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		return Ref<X86_64InterpreterFrame>.of(CiRuntime.forgeRange<byte>(sp, X86_64InterpreterFrame.size));
                                                                ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 27:61] UnresolvedMember: type CiRuntime has no such member "forgeRange"
			platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(bytes)));
                                                            ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 61:53] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(cur_bytes + add_bytes)));
                                                    ^^^^^^^^^^
[src/monitors/MemStatsMonitor.v3 @ 124:30] ParseError: ',' or ';' expected
def log2_WASM_PAGE_SIZE = 16u6;
                             ^
cp: cannot stat 'bin/wizeng.x86-64-linux': No such file or directory
warning: could not pregen code into bin/wizeng.x86-64-linux, may be slower (see bin/wizeng.x86-64-linux.pregen)
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:35] UnresolvedMember: type Pointer has no such member "atRef"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                  ^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:56] UnresolvedOp: operator "+" cannot be found for type "?"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                                       ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:46] UnresolvedOp: operator "-" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:62] UnresolvedOp: operator "&" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:40] TypeError: type cast always fails
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                       ^
[src/engine/x86-64/X86_64Stack.v3 @ 725:65] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		return Ref<X86_64InterpreterFrame>.of(CiRuntime.forgeRange<byte>(sp, X86_64InterpreterFrame.size));
                                                                ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 27:61] UnresolvedMember: type CiRuntime has no such member "forgeRange"
			platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(bytes)));
                                                            ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 61:53] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(cur_bytes + add_bytes)));
                                                    ^^^^^^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:35] UnresolvedMember: type Pointer has no such member "atRef"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                  ^^^^^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 140:56] UnresolvedOp: operator "+" cannot be found for type "?"
		var ptr = Pointer.atRef(pregen_header) + X86_64PreGenHeader.magicWord.offset;
                                                       ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:46] UnresolvedOp: operator "-" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:62] UnresolvedOp: operator "&" cannot be found for type "?"
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                                             ^
[src/engine/x86-64/X86_64PreGenStubs.v3 @ 141:40] TypeError: type cast always fails
		var page_offset = int.!((ptr - Pointer.NULL) & (PAGE_SIZE - 1));
                                       ^
[src/engine/x86-64/X86_64Stack.v3 @ 725:65] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		return Ref<X86_64InterpreterFrame>.of(CiRuntime.forgeRange<byte>(sp, X86_64InterpreterFrame.size));
                                                                ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 27:61] UnresolvedMember: type CiRuntime has no such member "forgeRange"
			platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(bytes)));
                                                            ^^^^^^^^^^
[src/engine/x86-64/X86_64Memory.v3 @ 61:53] UnresolvedMember: type CiRuntime has no such member "forgeRange"
		platform_specific_setData(CiRuntime.forgeRange<byte>(start, int.!(cur_bytes + add_bytes)));
                                                    ^^^^^^^^^^
[src/monitors/MemStatsMonitor.v3 @ 124:30] ParseError: ',' or ';' expected
def log2_WASM_PAGE_SIZE = 16u6;

**Comment by titzer** [comment]
Hello,

You'll need to bootstrap Virgil first, because Wizard uses features that are not in stable:

```
% cd <your-virgil-checkout>
% make -j
```

**Comment by ggnery** [comment]
When i run `make` in virgil folder i get an error that says 
`
/bin/sh: 1: v3c-host: not found
make: *** [Makefile:9: bin/utils/vctags] Error 127
`
Obs: I have executed the following code before running make:

`
% cd virgil
% git pull
Already up to date.
% bin/dev/aeneas clean
% bin/dev/aeneas bootstrap
`

Here is my log: 
`
bin/dev/aeneas bootstrap
Compiling (/home/gnery/Desktop/Projeto_pesquisa/virgil/bin/stable/x86-linux/Aeneas -> /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/bootstrap/x86-linux/Aeneas)...
-rwxr-xr-x 1 gnery gnery 2331092 mai  1 15:58 /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/bootstrap/x86-linux/Aeneas
Compiling (/home/gnery/Desktop/Projeto_pesquisa/virgil/bin/bootstrap/x86-linux/Aeneas -> /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/current/x86-linux/Aeneas)...
-rwxr-xr-x 1 gnery gnery 2324080 mai  1 15:58 /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/current/x86-linux/Aeneas
Compiling (/home/gnery/Desktop/Projeto_pesquisa/virgil/bin/bootstrap/x86-linux/Aeneas -> /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/current/x86-64-linux/Aeneas)...
-rwxr-xr-x 1 gnery gnery 2266456 mai  1 15:58 /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/current/x86-64-linux/Aeneas
Compiling (/home/gnery/Desktop/Projeto_pesquisa/virgil/bin/bootstrap/x86-linux/Aeneas -> /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/current/jar/Aeneas)...
-rwxr-xr-x 1 gnery gnery     290 mai  1 15:58 /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/current/jar/Aeneas
-rw-r--r-- 1 gnery gnery 3876968 mai  1 15:58 /home/gnery/Desktop/Projeto_pesquisa/virgil/bin/current/jar/Aeneas.jar
(cd apps/vctags && v3c-host -output=../../bin/utils/ *.v3 `cat DEPS`)
/bin/sh: 1: v3c-host: not found
make: *** [Makefile:9: bin/utils/vctags] Error 127
`
