### ISSUE TITLE
vctags not found

### ISSUE THREAD

**Issue by ggnery** [titzer/wizard-engine#160]
#159 I have compiled virgil. But when i try to use make in wizard, i get this error

![image](https://github.com/titzer/wizard-engine/assets/101832203/4607ebd7-aeab-456b-874c-01bd79442581)

**Comment by titzer** [comment]
You may also need to do `make utils` in the Virgil repo and add `virgil/bin/utils` to your path.

**Comment by ggnery** [comment]
Ok, after building utils I got this make error

![image](https://github.com/titzer/wizard-engine/assets/101832203/66c7bb21-ee58-452d-86c5-75ff6891556a)

**Comment by titzer** [comment]
That looks like it completed successfully.
