### ISSUE TITLE
`make` fails on Apple Silicon

### ISSUE THREAD

**Issue by samestep** [titzer/wizard-engine#187]
Followup on #184. After 776040457cf6e0fb18f45d2e952675f73a3c3bc6, I can build Virgil just fine, but [running `make` for Wizard itself](https://github.com/titzer/wizard-engine/blob/b9d0e88cd768d5464442be87fd2925b8aedbfdc8/doc/Building.md#build-wizard-with-make) fails with this error:

```
% git clone git@github.com:titzer/wizard-engine.git
% cd wizard-engine
% make -j
./build.sh spectest x86-linux
./build.sh wizeng x86-linux
./build.sh unittest x86-linux
./build.sh objdump x86-linux
./build.sh spectest x86-64-linux
./build.sh wizeng x86-64-linux
./build.sh unittest x86-64-linux
./build.sh objdump x86-64-linux
./build.sh spectest jvm
./build.sh wizeng jvm
./build.sh unittest jvm
./build.sh objdump jvm
warning: could not pregen code into bin/wizeng.x86-64-linux, may be slower (see bin/wizeng.x86-64-linux.pregen)
```

It does seem to have successfully built Wizard, though:

```
% bin/wizeng.jvm --version
Wizard Engine 24α.2225
Build data: jvm 2024-09-10 08:50:05 by samueles@
wizeng: no input files
```

**Comment by titzer** [comment]
It's warning, but given that the host platform cannot run one of the intermediate binaries, the warning should probably be suppressed for some hosts.
