### ISSUE TITLE
expected 3 data segments, missing data section

### ISSUE THREAD

**Issue by doehyunbaek** [titzer/wizard-engine#204]
It seems like wizard's behavior is different with other engines(wasmtime, wasmer)

```terminal
~/wasm-r3/benchmarks/commanderkeen wizeng.x86-64-linux --version
Wizard Engine 24α.2292
Build data: x86-64-linux 2024-10-07 22:03:43 by don@
wizeng: no input files
~/wasm-r3/benchmarks/commanderkeen wizeng.x86-64-linux commanderkeen-187.wasm 
commanderkeen-187.wasm:0xDC03: expected 3 data segments, missing data section
~/wasm-r3/benchmarks/commanderkeen wasmtime --invoke main commanderkeen-187.wasm 
~/wasm-r3/benchmarks/commanderkeen wasmer commanderkeen-187.wasm 

~/wasm-r3/benchmarks/commanderkeen 
```
[commanderkeen-187.wasm.zip](https://github.com/user-attachments/files/17278956/commanderkeen-187.wasm.zip)

**Comment by titzer** [comment]
Is there a way to try this on V8? I suspect this has to do with pre-declared data segments.

**Comment by doehyunbaek** [comment]
D8 also emits error, albeit a different one.

I made a repro repo:

**Comment by titzer** [comment]
It looks like there are multiple problems with that wasm file; a function that is too large and some missing data segments. AFAICT the difference between V8 and Wizard is which one is reported first.
