### ISSUE TITLE
Calls monitor should use FrameAccessor.depth

### ISSUE THREAD

**Issue by titzer** [titzer/wizard-engine#7]

**Comment by titzer** [comment]
@btwj Do you want to fix this one?

**Comment by btwj** [comment]
Yeah, I could do this. One complication though, we might still need the calls monitor to track its own depth if we're tracing calls matching a glob, because then the depth would be with respect to traced functions only. Do you have something else in mind for that?

**Comment by titzer** [comment]
Ah, that's a good point. Current behavior is probably more intuitive atm.
